dire/order/urls.py
from django.urls import path
from . import views


app_name = "order"

urlpatterns = [
    # /order/
    path('', views.IndexView.as_view() , name='orderIndex'),

    # /order/:id
    path('<pk>', views.DetailView.as_view(), name='orderDetail'),

    # /order/create
    path('add/', views.CreateOrder, name='orderCreate'),

    # /order/success
    path('success/', views.SuccessfulOrder, name='orderSuccess'),

    # /order/:id/edit/
    path('<pk>/edit/', views.UpdateOrder.as_view(), name='orderUpdate'),

    # /order/:id/delete/
    path('<pk>/delete/', views.DeleteOrder.as_view(), name='orderDelete')
]

dire/project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="home"),
    path('order/', include('order.urls')),
    path('accounts/', include('accounts.urls'))
]

dire/order/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Order(models.Model):
    starting_point = models.CharField(max_length=400)
    destination_point = models.CharField(max_length=400)
    sender_name = models.CharField(max_length=400)
    sender_phonum = models.CharField(max_length=400)
    recipient_name = models.CharField(max_length=400)
    recipient_phonum = models.CharField(max_length=400)
    #status ordered, on process, delivered
    status = models.CharField(max_length=400)
    courier = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='couriers')
    userid = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='users')

    def get_absolute_url(self):
        return reverse('order:orderDetail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ["id"]

dire/order/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order
from django.contrib.auth.decorators import login_required

# Create your views here.

class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = 'accounts:accountsLogin'
    template_name = 'order/index.html'
    slug = 'test'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['some_thing'] = self.request.user.is_authenticated
        return data

    def get_queryset(self):
        return Order.objects.all()

class DetailView(generic.DetailView):
    model = Order
    template_name = 'order/detail.html'

@login_required
def CreateOrder(request):
    return render(request, 'order/order_form.html')

def SuccessfulOrder(request):
    if request.method=="POST":
        order = Order()
        order.userid = request.user
        
        order.starting_point = request.POST["starting_order"]
        order.destination_point = request.POST["destination_order"]

        order.sender_name = request.POST["sender_name"]
        order.sender_phonum = request.POST["sender_phonum"]
        order.recipient_name = request.POST["recipient_name"]
        order.recipient_phonum = request.POST["recipient_phonum"]

        order.status = 'ordered'

        order.save()
        return render(request, 'order/order_success.html')

class UpdateOrder(UpdateView):
    model = Order
    fields = ['starting_point','destination_point']

class DeleteOrder(DeleteView):
    model = Order
    success_url = reverse_lazy('order:orderIndex')

'''
def index(request):
    all_order = Order.objects.all()
    context = {
        'all_order' : all_order,
    }
    return render(request, 'order/index.html', context)

def detail(request, order_id):
    try:
        order = Order.objects.get(id=order_id)
    except Order.DoesNotExist:
        raise Http404('Order doesnt exist')
    return HttpResponse('<h1>Detail of ' + str(order_id) + '</h1>')
'''

dire/templates/order/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dire {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'order/style.css' %}">
</head>
<body>

<header>

</header>

{% block body %}

{% endblock %}

<footer>

</footer>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

dire/templates/order/detail.html
{% extends "application.html" %}

{% block title %}
Welcome to Dire!
{% endblock %}
{% block content %}

{% load static %}

    <div class="container">
  <table border="0" cellpadding="0" cellspacing="3">
        <tr>
            <td colspan="2">
                Source:
                <input type="text" id="txtSource" value="Bandra, Mumbai, India" style="width: 200px" />
                &nbsp; Destination:
                <input type="text" id="txtDestination" value="Andheri, Mumbai, India" style="width: 200px" />
                <br />
                <input type="button" value="Submit" onclick="GetRoute()" />
                <hr />
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <div id="dvDistance">
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div id="dvMap" style="width: 1300px; height: 500px">
                </div>
            </td>
            
        </tr>
    </table>
       <!-- <h1> Order Number: {{ order.id }} </h1>
        Starting Point : {{ order.starting_point }} <br/>
        Destination Point : {{ order.destination_point }} <br> 

        <a href="{% url 'order:orderIndex' %}"><<< back</a>  
        <input id="from" type="text" style="width:100%" placeholder="dari">
        <input id="to" type="text" style="width:100%" placeholder="tujuan">
       <input type='button' onclick="setTimeout(myMap, 3000);">submit</input> 
        <div id="map" style="width:100%;height:500px"></div> -->

    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>
    <script type="text/javascript">
        var source, destination;
        var directionsDisplay;
        var directionsService = new google.maps.DirectionsService();
        google.maps.event.addDomListener(window, 'load', function () {
            new google.maps.places.SearchBox(document.getElementById('txtSource'));
            new google.maps.places.SearchBox(document.getElementById('txtDestination'));
            directionsDisplay = new google.maps.DirectionsRenderer({ 'draggable': true });
        });

        function GetRoute() {
              var directionsService = new google.maps.DirectionsService;
              var directionsDisplay = new google.maps.DirectionsRenderer;
              var map = new google.maps.Map(document.getElementById('dvMap'), {
                zoom: 10,
                center: {lat: 41.85, lng: -87.65}
              });
              directionsDisplay.setMap(map);
            //mumbai = new google.maps.LatLng(18.9750, 72.8258);
            //var mapOptions = {
              //  zoom: 7,
              //  center: mumbai
           // };
            // map = new google.maps.Map(document.getElementById('dvMap'), mapOptions);
           // directionsDisplay.setMap(map); 
           

            //*********DIRECTIONS AND ROUTE**********************//
            source = document.getElementById("txtSource").value;
            destination = document.getElementById("txtDestination").value;

            var request = {
                origin: source,
                destination: destination,
                travelMode: google.maps.TravelMode.DRIVING
            };
            directionsService.route(request, function (response, status) {
                if (status == google.maps.DirectionsStatus.OK) {
                    directionsDisplay.setDirections(response);
                }
            });

            //*********DISTANCE AND DURATION**********************//
            var service = new google.maps.DistanceMatrixService();
            service.getDistanceMatrix({
                origins: [source],
                destinations: [destination],
                travelMode: google.maps.TravelMode.DRIVING,
                unitSystem: google.maps.UnitSystem.METRIC,
                avoidHighways: false,
                avoidTolls: false
            }, function (response, status) {
                if (status == google.maps.DistanceMatrixStatus.OK && response.rows[0].elements[0].status != "ZERO_RESULTS") {
                    var distance = response.rows[0].elements[0].distance.text;
                    var duration = response.rows[0].elements[0].duration.text;
                    var dvDistance = document.getElementById("dvDistance");
                    dvDistance.innerHTML = "";
                    dvDistance.innerHTML += "Distance: " + distance + "<br />";
                    dvDistance.innerHTML += "Duration:" + duration;

                } else {
                    alert("Unable to find the distance via road.");
                }
            });
        }
    </script>
   <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDxnaq11J1ZmAOz5QZ5nRG2oDF9eegw5qQ&callback=GetRoute">
    </script>
  
  </div>


{% endblock %}

dire/templates/order/index.html
{% extends "application.html" %}

{% block title %}
List of Order
{% endblock %}
{% block content %}

{% load static %}

    <div class="container">

        <h1> All Order</h1>
        {% for eachOrder in object_list %}
            <a href="{% url 'order:orderDetail' eachOrder.id %}">
                {{ eachOrder.id }} - {{ eachOrder.starting_point }} - {{ eachOrder.destination_point }}
            </a><br/>

        {% endfor %}
        {% if some_thing %}
          <h2> Create New Order </h2>
          <a href="{% url 'order:orderCreate' %}">
              <button type="button" class="btn btn-outline-primary">New</button>
          </a>
          
        {% endif %}
    </div>

{% endblock %}

dire/templates/order/order_form.html
{% extends "application.html" %}

{% block title %}
Welcome to Dire!
{% endblock %}
{% block content %}

{% load static %}

<div class="container">
	<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">

    <h1 class="h1-title"> Create Order</h1>

    <div class="row">
      <div class="col-md-6">
        Sender Name<br/>
        <input id="sendername-input" class="controls main-input w-50" type="text"
        placeholder="Sender Name">
      </div>
      <div class="col-md-6">
        Recipient Name<br/>
        <input id="recipientname-input" class="controls main-input w-50" type="text"
        placeholder="Recipient Name">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        Sender Phone Number<br/>
        <input id="senderphonum-input" class="controls main-input w-50" type="text"
        placeholder="Sender Phone Number">
      </div>
      <div class="col-md-6">
        Recipient Phone Number<br/>
        <input id="recipientphonum-input" class="controls main-input w-50" type="text"
        placeholder="Recipient Phone Number">
      </div>
    </div>
    
    Starting Point<br/>
    <input id="origin-input" class="controls main-input w-50" type="text"
        placeholder="Enter an origin location">

    <br/>Destination Point<br/>
    <input id="destination-input" class="controls main-input w-50" type="text"
        placeholder="Enter a destination location">

    <div id="mode-selector" class="controls">
      <input type="radio" name="type" id="changemode-walking" checked="checked" value="Walking">
      <label for="changemode-walking">Walking</label>

      <input type="radio" name="type" id="changemode-transit" value="Transit">
      <label for="changemode-transit" >Transit</label>

      <input type="radio" name="type" id="changemode-driving" value="Driving">
      <label for="changemode-driving" >Driving</label>
    </div>

    <div id="map"></div>

    <div id="dvDistance">
    </div>

    <button id="confirmationButton" type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModalCenter">Confirm</button>

    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLongTitle">Confirm</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	        <form action="{% url 'order:orderSuccess' %}" method="POST">
            {% csrf_token %}
            <input class="main-input" name="starting_order" type="hidden" value="" id="starting_point">
            <input class="main-input" name="destination_order" type="hidden" value="qwer" id="destination_point">
            <input class="main-input" name="sender_name" type="hidden" value="qwer" id="id_sender_name">
            <input class="main-input" name="sender_phonum" type="hidden" value="qwer" id="id_sender_phonum">
            <input class="main-input" name="recipient_name" type="hidden" value="qwer" id="id_recipient_name">
            <input class="main-input" name="recipient_phonum" type="hidden" value="qwer" id="id_recipient_phonum">

            <div class="row">
              <div class="col-6">
                <h5>Sender</h5>
                <p id="order_sender"></p>
              </div>

              <div class="col-6">
                <h5>Recipient</h5>
                <p id="order_recip"></p>
              </div>

            </div>

            <div class="row">
              <div class="col-6">
                <h5>Starting Point</h5>
                <p id="order_start"></p>
              </div>

              <div class="col-6">
                <h5>Destination Point</h5>
                <p id="order_dest"></p>
              </div>

            </div>

            <hr/>

            <div class="row">
              <div class="col-6">Mode</div>
              <div class="col-6" id="order_mode">: Walking</div>
            </div>

            <div class="row">
              <div class="col-6">Distance</div>
              <div class="col-6" id="order_distance">: 5 km</div>
            </div>

            <div class="row">
              <div class="col-6">Duration</div>
              <div class="col-6" id="order_duration">: 15 mins</div>
            </div>

            <div class="row">
              <div class="col-6">Price</div>
              <div class="col-6">: 10$</div>
            </div>

            <input type="submit" class="btn btn-primary">

          </form>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        
	      </div>
	    </div>
	  </div>
	</div>

</div>

<script type="text/javascript" src="{% static 'js/form.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDxnaq11J1ZmAOz5QZ5nRG2oDF9eegw5qQ&libraries=places&callback=initMap"
         async defer></script>


{% endblock %}

dire/templates/order/order_success.html
{% extends "application.html" %}

{% block title %}
Welcome to Dire!
{% endblock %}
{% block content %}

{% load static %}

<h1> Your order has been successfully created! </h1>

{% endblock %}