dire/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
	#sign up user
    path('signup', views.signupUser , name='accountsSignup'),

    #login user
    path('login', views.loginUser, name='accountsLogin'),

    #logout user
    path('logout', views.logoutUser, name='accountsLogout'),

    #create user
    path('create', views.createUser, name='createUser'),

    # create courier
    path('createcourier', views.createcourier, name='createcourier'),

    # profile page
    path('profile', views.profile, name='userprofile'),

    # signup courier
    path('courier/signup', views.signupcourier, name='signupcourier'),

    #home for registered user
    path('', views.index, name='accountshome')
]

dire/order/urls.py
from django.urls import path
from . import views


app_name = "order"

urlpatterns = [
    # /order/
    path('', views.IndexView.as_view() , name='orderIndex'),

    # /order/:id
    path('<pk>', views.DetailView.as_view(), name='orderDetail'),

    # /order/create
    path('add/', views.CreateOrder, name='orderCreate'),

    # /order/success
    path('success/', views.SuccessfulOrder, name='orderSuccess'),

    # /order/:id/edit/
    path('<pk>/edit/', views.UpdateOrder.as_view(), name='orderUpdate'),

    # /order/:id/delete/
    path('<pk>/delete/', views.DeleteOrder.as_view(), name='orderDelete')
]

dire/project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="home"),
    path('order/', include('order.urls')),
    path('accounts/', include('accounts.urls'))
]

dire/templates/application.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

    <!-- <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <meta charset="UTF-8">
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script> -->
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>

<style type="text/css">

</style>


</head>
<body>

<header>


  <nav class="navbar navbar-light bg-light">
    <div class="container">
      <div  class="col-md-1.5">
      {% if user.is_authenticated %}
      <a href='{% url "accounts:accountshome" %} '>
      {% else %}
      <a href='{% url "home" %} '>
      {% endif %}
      <img src="{% static 'img/final-logo.svg' %}" alt='logo' style='width:100px; height:55px;' />
      </a>
      </div>


      <div  class='col-md-1.5'>

        <a href='#' class="nav-menu-1">About Us</a>
        </div>

       <div  class='col-md-1.5'>
        <a href='#' class="nav-menu-1">Services</a>
        </div>

        <div  class='col-md-1.5'>
        <a href='#' class="nav-menu-1">FAQ</a>
        </div>

        {% if user.is_authenticated %}
        <div style="padding-top: 30px;" class='col-md-6'>
           <div id="m-link-signup" class="float-right" >
            <form action="{% url 'accounts:accountsLogout' %}">
              {% csrf_token %}
              <input type="submit" name="" value="LOGOUT" class="input-nav">
            </form>
          </div>

          <div id="m-link-signup" class="float-right" >
            <a href="{% url 'accounts:userprofile' %}">PROFILE</a>
          </div>

        </div>

        {% else %}
        <div style="padding-top: 30px;" class='col-md-6'>

          <div id="m-link-signup" class="float-right" >
            <a href="#" data-toggle="modal" data-target="#modalLogin">LOGIN</a>
            <div class="modal fade" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="modalLogin" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Login </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body main-modal-body">
                    <form action="{% url 'accounts:accountsLogin' %}" method="POST">
                      {% csrf_token %}
                      Username:
                      <input type="text" class="main-input w-100" placeholder="E-MAIL ADDRESS" name="username" required>
                      Password:
                      <input type="password"  class="main-input w-100" placeholder="PASSWORD" name="password" required>
                      <p class="main-modal-p">Not yet a Dire member? 
                      <a href="#" style='font-size: 12px; color: #3E664B;'>REGISTER HERE</a>
                      </p>
                      <input type="submit" class="main-button btn btn-success" style="width: 15%; background-color: #3E664B " value="Login">
                    </form>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    
                  </div>
                </div>
              </div>
            </div>

          </div>

          <div id="m-link-signup" class="float-right" >
            <a href="{% url 'accounts:accountsSignup' %}">REGISTER</a>
          </div>

          <div id="m-link-signup" class="float-right" >
            <a style='color: #E84C4C;' href="#">JOIN US</a>
          </div>


        </div>

        {% endif %}
      </div>
    </div>
  </div>
  
  </nav>

</header>
{% block content %}{% endblock %}

<footer>
  <div class="container">
    <div class="row justify-content-center">
        <div style="padding-top: 30px; text-align: left; " class="col-md-6">
        <img src="{% static 'img/final-logo.svg' %}" alt='logo' style='width:200px; height:110px;' />
        </div>

        <div class="footer-menu-1" class='col-md-1.5'>
        <a href='#'><b>Contact Us</b></a>
        </div>

        <div class="footer-menu-1" class='col-md-1.5'>
        <a href="#"><b>Terms & Condition</b></a>
        </div>

        <div class="footer-menu-1" class='col-md-1.5'>
        <a href="#"><b>Privacy Policy</b></a>
        </div>

        <div class="footer-menu-1" class='col-md-1.5'>
        <a href="#"><b>About Us</b></a>
        </div>
    </div>
  </div>
   <div class="footer-copyright">
    <p style="font-size: 13px"><b>Copyright by DIRE 2018</b></p>
  </div>

  <hr style='background-color: black; height: 0.5px; width: 95%'>
</footer>
 


<!-- script to get the login modal -->
<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>


<!-- Compiled and minified JavaScript -->


</body>
</html>

dire/templates/index.html
{% extends "application.html" %}

{% block title %}
Welcome to Dire!
{% endblock %}
{% block content %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

<div class="row">

  <div class="col-md-6">
    <section id="introduction" style="background: linear-gradient(to top, rgba(55, 102, 55,1), rgba(0,0,0,0.8)), url({% static 'img/try-1.jpg' %}) 0% 0%/cover">
     <div class="container" style="padding-left: 20%;">
       <div class="row fill-95-viewport align-items-center">
         <div class="col-12 col-md-6">
           <h1 class="text-white">What is</h1>
           <h1 class="text-white">Dire? <span></span></h1>
           <p class="text-white-70 text-80">
             Dire is an instant courier to send items and documents quickly without bothering to travel from places on our own. Dire also provide other service by doing errands from people to buy their needs in certain location nearby the area. </p>
           <a class="btn" id="m-btn-banner" href="#" role="button">More about us</a>
         </div>
       </div>
     </div>
    </section>
  </div>
  <div class="col-md-6">
    <section id="introduction" style="background: linear-gradient(to top, rgba(255, 255, 255,1), rgba(0,0,0,0.8)), url({% static 'img/try-2.jpg' %}) 0% 0%/cover">
     <div class="container" style="padding-left: 20%;">
       <div class="row fill-95-viewport align-items-center">
         <div class="col-12 col-md-6">
           <h1 class="text-white">How to </h1>
           <h1 class="text-white">Order? <span></span></h1>
           <p class="text-white-70 text-80">
             Dire is an instant courier to send items and documents quickly without bothering to travel from places on our own. Dire also provide other service by doing errands from people to buy their needs in certain location nearby the area. </p>
           <a class="btn" id="m-btn-banner" href="#" role="button">Make an order</a>
         </div>
       </div>
     </div>
    </section>
  </div>
</div>


<div class="row content-2 fill-80-viewport">
  <div class="col-md-6">
    <p class="content2-title">ABOUT DIRE </p>
    <br>
    <h4 class="content2-h4">WE SHALL NEVER LET YOUR TIME WASTED ON THE ROAD</h4>
    <br>
    <p class="content2-p">Dire is an instant courier to send items and documents quickly without bothering to travel from places on our own. Dire also provide other service by doing errands from people to buy their needs in certain location nearby the area. Customers can pick the type of transportation they wish the package would be delivered, the price should be adjusted according to the vehicle and the distance between points.</p>
    <p class="content2-p">This online services was created to help people who needs to deliver, taking or buying items in other places without any hesitation to do this on their own. We hope that the services can help people to reduce their time on travel from places to places and in result cutting their cost to travel.</p>
  </div>
  <div class="col-md-6">
      <img src="{% static 'img/parcelServices.jpg' %}" alt='about us' class="content2-img" />
  </div>
 </div>

<div class="content-3">
  <div class="row justify-content-center"> 
    <div style='width:150px; background-color: #2D2C2C;'>
      <div class="col-md-12">
        <div class="content3-title1">
        <p class="content3-title2">OUR SERVICES </p>
        </div>
      </div>
   </div>
  </div>

  <div class="row justify-content-center" style="padding-bottom: 100px;">
    <div style='width:80%; '>
      <div class='col-md-3'>
      <p style="margin-top: 50px; line-height: 41px; color: white; letter-spacing:20px; font-weight: 500; font-size: 30px; margin-left: 230px; writing-mode: vertical-rl; text-orientation: upright;">SHOP</p>
      </div>
      <div class='col-md-3'>
      <div style='width:250px; margin-bottom:-300px; margin-left: 300px; margin-top: -200px; background-color:#C4C4C4;  box-shadow: 10px 10px 10px #a33535;'>
      <img src="{% static 'img/shop.jpg' %}" alt='about us' style='width: 250px; height: 300px;' />
      <br>
      <a href="#" style="width: 250px; letter-spacing: 2px; color: #3E664B; padding-top: 5px;padding-bottom:5px; padding-left:5px; font-size: 12px; font-weight: 600;">READ MORE ----></a>
      </div>
      </div>
      <div class='col-md-3'>
      <div style='width:250px; margin-bottom:-80px; margin-left: 790px; margin-top: -320px; background-color:#C4C4C4; box-shadow: 10px 10px 10px #a33535;'>
      <img src="{% static 'img/try-1.jpg' %}" alt='about us' style='width: 250px; height: 300px;' />
      <a href="#" style="width: 250px; letter-spacing: 2px; color: #3E664B; padding-top: 5px; padding-bottom:5px; padding-left:5px; font-size: 12px; font-weight: 600;">READ MORE ----></a>
      </div>
      </div>
      <div class='col-md-3'>
      <p style="margin-top: -355px;  line-height: 41px; color: white; letter-spacing:20px; font-weight: 500; font-size: 30px; margin-left: 720px; writing-mode: vertical-rl; text-orientation: upright;">COURIER</p>
      </div>
    </div>
  </div>
</div>


{% endblock %}