dire/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
	#sign up user
    path('signup', views.signupUser , name='accountsSignup'),

    #login user
    path('login', views.loginUser, name='accountsLogin'),

    #logout user
    path('logout', views.logoutUser, name='accountsLogout'),

    #create user
    path('create', views.createUser, name='createUser'),

    # create courier
    path('createcourier', views.createcourier, name='createcourier'),

    # profile page
    path('profile', views.profile, name='userprofile'),

    # signup courier
    path('courier/signup', views.signupcourier, name='signupcourier'),

    #home for registered user
    path('', views.index, name='accountshome')
]

dire/order/urls.py
from django.urls import path
from . import views


app_name = "order"

urlpatterns = [
    # /order/
    path('', views.IndexView.as_view() , name='orderIndex'),

    # /order/:id
    path('<pk>', views.DetailView.as_view(), name='orderDetail'),

    # /order/create
    path('add/', views.CreateOrder, name='orderCreate'),

    # /order/success
    path('success/', views.SuccessfulOrder, name='orderSuccess'),

    # /order/:id/edit/
    path('<pk>/edit/', views.UpdateOrder.as_view(), name='orderUpdate'),

    # /order/:id/delete/
    path('<pk>/delete/', views.DeleteOrder.as_view(), name='orderDelete')
]

dire/project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="home"),
    path('order/', include('order.urls')),
    path('accounts/', include('accounts.urls'))
]

dire/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	usertype = models.BooleanField(default=False)
	bio = models.CharField(max_length=1000)
	phonum = models.CharField(max_length=15)
	city = models.CharField(max_length=30)
	# 1 for courier, 0 for normal user

	def __str__(self):
		return self.user.username

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

dire/accounts/forms.py
'''class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('url', 'location', 'company')'''

dire/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate, login
from django.contrib.auth.models import User
from django.db import models
from .models import UserProfile
from order.models import Order

# Create your views here.
def signupUser(request):
    return render(request, 'accounts/signup.html')
    '''form = UserCreationForm(request.POST)
    if form.is_valid():
        user = form.save()
        login(request, user)
        return redirect("home")'''

def createUser(request):
    if request.method == 'POST':
        usertype = 0
        firstname = request.POST["user-firstname"]
        lastname = request.POST["user-lastname"]
        email = request.POST["user-email"]
        username = request.POST["user-username"]
        password = request.POST["user-password"]
        phonum = request.POST["user-phonum"]
        city = request.POST["user-city"]
        reg_user = authenticate(request, username=username, password=password)
        if reg_user is not None:
            return HttpResponseRedirect(reverse('accounts:accountsSignup'))
        else:
            userdb = User.objects.create_user( username=username, email=email, password=password, first_name=firstname, last_name=lastname)
            
            print(userdb.id)
            profile = UserProfile()
            profile.user_id = userdb.id
            profile.phonum = phonum
            profile.city = city
            userdb.save()
            profile.save()
            return HttpResponseRedirect(reverse('accounts:accountshome'))

def signupcourier(request):
    return render(request, 'accounts/signup-courier.html')

def createcourier(request):
    if request.method == 'POST':
        usertype = True
        firstname = request.POST["user-firstname"]
        lastname = request.POST["user-lastname"]
        email = request.POST["user-email"]
        username = request.POST["user-username"]
        password = request.POST["user-password"]
        phonum = request.POST["user-phonum"]
        city = request.POST["user-city"]
        reg_user = authenticate(request, username=username, password=password)
        if reg_user is not None:
            return HttpResponseRedirect(reverse('accounts:accountsSignup'))
        else:
            userdb = User.objects.create_user( username=username, email=email, password=password, first_name=firstname, last_name=lastname)
            
            print(userdb.id)
            profile = UserProfile()
            profile.usertype = usertype
            profile.user_id = userdb.id
            profile.phonum = phonum
            profile.city = city
            userdb.save()
            profile.save()
            return HttpResponseRedirect(reverse('accounts:accountshome'))

def loginUser(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("home")
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form' : form})

def logoutUser(request):
    logout(request)
    return redirect('home')

def profile(request):
    username = None
    context = {}
    if request.user.is_authenticated:
        user = request.user
        context = {'user':user}
    return render(request, 'accounts/profile.html', context)

def index(request):
    username = None
    context = {}
    if request.user.is_authenticated:
        user = request.user
        if user.userprofile.usertype:
            order = Order.objects.filter(status="ordered")
            myorder = user.couriers.all()
            context = {'user':user, 'order':order, 'myorder':myorder}
        else:
            order = user.users.all()
            context = {'user':user, 'order':order}
    return render(request, 'accounts/index.html', context)

dire/templates/accounts/index.html
{% extends "application.html" %}

{% block title %}
Profile
{% endblock %}
{% block content %}

{% load static %}

<div class="container">
	{% if user.userprofile.usertype %}
	<h1 class="h1-title"> Hi {{user.first_name}} ! </h1>
	{{user.username}}<br>
	{{user.id}}<br>
	
	Lastname : {{user.last_name}}<br>
	Email	 : {{user.email}}<br>
	phonum	 : {{user.userprofile.phonum}}<br>
	city	 : {{user.userprofile.city}}<br>

	You can take these order!<br/>
	{% for eachorder in order %}
		{{ eachorder.id }}, {{ eachorder.starting_point }} - {{ eachorder.destination_point }}<br/>
	{% endfor %}

	Your current jobs:<br/>
	{% for eachorder in myorder %}
		{{ eachorder.id }}, {{ eachorder.starting_point }} - {{ eachorder.destination_point }}<br/>
	{% endfor %}


	{% else %}
	<h1 class="h1-title"> Hi {{user.first_name}} ! </h1>
	{{user.username}}<br>
	{{user.id}}<br>
	
	Lastname : {{user.last_name}}<br>
	Email	 : {{user.email}}<br>
	phonum	 : {{user.userprofile.phonum}}<br>
	city	 : {{user.userprofile.city}}<br>

	<br/>
	Your Order:<br/>
	{% for eachorder in order %}
		{{ eachorder.id }}, {{ eachorder.starting_point }} - {{ eachorder.destination_point }}<br/>
	{% endfor %}

	<br/>
	<br/>

	<a href="{% url 'order:orderCreate' %}">Make new order</a>

	{% endif %}
	
	
</div>


{% endblock %}

dire/templates/accounts/login.html
{% extends "application.html" %}

{% block title %}
Login
{% endblock %}
{% block content %}

{% load static %}
<div class="container">
  <h1> Login </h1>
  <form class="site-form" action="{% url 'accounts:accountsLogin' %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="" value="Sign Up">
  </form>
</div>

{% endblock %}

dire/templates/accounts/profile.html
{% extends "application.html" %}

{% block title %}
Profile
{% endblock %}
{% block content %}

{% load static %}

<div class="container">
	<h1 class="h1-title"> Profile #{{user.id}} </h1>
	{{user.username}}<br>
	Firstname: {{user.first_name}}<br>
	Lastname : {{user.last_name}}<br>
	Email	 : {{user.email}}<br>
	phonum	 : {{user.userprofile.phonum}}<br>
	city	 : {{user.userprofile.city}}<br>
	
</div>


{% endblock %}

dire/templates/accounts/signup-courier.html
{% extends "application.html" %}

{% block title %}
Sign Up
{% endblock %}
{% block content %}

{% load static %}
<div class="container">
  <h1 class="h1-title"> Sign up Courier </h1>
  <form class="site-form" action="{% url 'accounts:createcourier' %}" method="POST">
    {% csrf_token %}

    <div class="row" style="padding: 3% 1% 0px 0%">
        <div class="col-md-5">
            First Name<br/>
            <input name="user-firstname" class="controls main-input w-80" type="text"
        placeholder="Your First Name">
        </div>
        <div class="col-md-5">
            Last Name<br/>
            <input name="user-lastname" class="controls main-input w-80" type="text"
        placeholder="Your Last Name">
        </div>
    </div>
    
    Username<br/>
    <input name="user-username" class="controls main-input w-80" type="text"
placeholder="Username">

    <br/>Email<br/>
    <input name="user-email" class="controls main-input w-80" type="text"
placeholder="Email">
        
    <br/>Password<br/>
    <input name="user-password" class="controls main-input w-80" type="Password"
        placeholder="Your name">


    <div class="row" style="padding: 1% 1% 0px 0%">
        <div class="col-md-5">
            Phone Number<br/>
            <input name="user-phonum" class="controls main-input w-80" type="text"
        placeholder="Your name">
        </div>
        <div class="col-md-5">
            City<br/>
            <input name="user-city" class="controls main-input w-80" type="text"
        placeholder="Your name">
        </div>
    </div>
    <br/>
    <input type="submit" class="btn btn-primary" value="Sign Up">
  </form>
</div>

{% endblock %}

dire/templates/accounts/signup.html
{% extends "application.html" %}

{% block title %}
Sign Up
{% endblock %}
{% block content %}

{% load static %}
<div class="container">
  <h1 class="h1-title"> Sign up </h1>
  <form class="site-form" action="{% url 'accounts:createUser' %}" method="POST">
    {% csrf_token %}

    <div class="row" style="padding: 3% 1% 0px 0%">
        <div class="col-md-5">
            First Name<br/>
            <input name="user-firstname" class="controls main-input w-80" type="text"
        placeholder="Your First Name">
        </div>
        <div class="col-md-5">
            Last Name<br/>
            <input name="user-lastname" class="controls main-input w-80" type="text"
        placeholder="Your Last Name">
        </div>
    </div>
    
    Username<br/>
    <input name="user-username" class="controls main-input w-80" type="text"
placeholder="Username">

    <br/>Email<br/>
    <input name="user-email" class="controls main-input w-80" type="text"
placeholder="Email">
        
    <br/>Password<br/>
    <input name="user-password" class="controls main-input w-80" type="Password"
        placeholder="Your name">


    <div class="row" style="padding: 1% 1% 0px 0%">
        <div class="col-md-5">
            Phone Number<br/>
            <input name="user-phonum" class="controls main-input w-80" type="text"
        placeholder="Your name">
        </div>
        <div class="col-md-5">
            City<br/>
            <input name="user-city" class="controls main-input w-80" type="text"
        placeholder="Your name">
        </div>
    </div>
    <br/>
    <input type="submit" class="btn btn-primary" value="Sign Up">
  </form>
</div>

{% endblock %}